---
# List of plugin entries. Each entry must include: name, repo, branch (optional)
plugins:
  - name: "nautobot-demo-plugin"
    repo: "https://github.com/AkhilMohammed/nautobot-deploy.git"
    branch: "feat/intial"

# Optional: docker image tag for the combined image
combined_image_tag: "latest"

# GHCR credentials will be passed as secrets/env; provide as extra-vars in workflow
# github_token: "{{ lookup('env','GHCR_TOKEN') }}"
#new line werwjghkffjlkgfkdknfjdaddckdjhhkklsk
