---
- name: Deploy Nautobot stack on target host(s)
  hosts: nautobot_servers
  become: true

  vars_files:
    - ../inventories/prod/group_vars/nautobot.yml

  roles:
    - docker-install
    - fetch_plugins
    - deploy-compose
